kind: Secret
apiVersion: v1
metadata:
  name: example-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/backend/stage"
type: Opaque
stringData:
  MONGO_URI_FULL: <path:secret/data/backend/stage#MONGO_URI>
  MONGO_URI: <MONGO_URI>
